services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: catering-gabay
      MYSQL_DATABASE: catering-gabay
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db-volume:
